name: GitHub Profile 3D Contribution Graph

on:
  schedule:
    # Runs every day at 18:00 UTC (this can be changed later)
    - cron: "0 18 * * *"
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest # The system to run the task
    name: Generate 3D Contribution Graph
    steps:
      # Checkout the repository to work with the files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Use the action that generates the 3D graph
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This can stay as GITHUB_TOKEN
          USERNAME: ${{ github.repository_owner }} # Your GitHub username

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "github-actions" # Set user for commits
          git config --global user.email "github-actions@github.com" # Set email for commits
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git # Reference the new token

      # Commit & Push
      - name: Commit & Push
        run: |
          git add -A . # Stage all changes
          git diff --cached --quiet || git commit -m "Generated 3D Contribution Graph" # Only commit if there are changes
          git push origin main # Push changes to the repository
